export const JOURNAL_STATUS_OPTIONS = [
  "approved",
  "Declined",
  "Denied",
  "Draft",
  "Hold",
  "Mail dispatched",
  "Mail submission",
  "Need alt text",
  "Need data and code disclosure policy",
  "Need human ethical statement",
  "Need institute email ID",
  "Need institute ID",
  "Need LaTeX file",
  "Need submission fee",
  "Out of scope",
  "Page issue",
  "pending",
  "rejected",
  "Removed",
  "Resubmit",
  "Revise and resubmit",
  "Revision",
  "submitted",
  "Submission returned to author",
  "Submission waiting for author's approval",
  "Submitted",
  "Successfully submitted",
  "Transfer",
  "under review",
  "Withdrawn",
  "With editor",
  "With journal administrator",
].sort(); // Sort alphabetically
